### ISSUE TITLE
請教Stepper的pathName是用在哪？

### ISSUE THREAD

**Issue by MikeLee0358** [lienweb/Alpha-Shop-Vue#1]
vue stepper的部分做起來卡關，不過觀摩同學的作業，發現架構很類似，也比我好很多。

我不解的地方是pathName，請問是透過哪個地方做路由切換的 (router我看你有設定呀)？
我嘗試過：
 用搜尋功能找pathName，只有OrderSubmit.vue才有。
我原本以為：
 版主是用<router-link>在下一步按鈕做切換，只是發現不是這麼一回事。

另外請教
  當遇到stepper這種，有狀態切換1/2/3會連動其他元件的區塊時，你在stepper階段是如何思考的？ 或是在拿到這個wireframe時，如何做整體思考的？
  
我：
   我會畫出每個component，若只是單純切畫面，是沒問題，只是再steppper要做邏輯連動時，哪個連動哪個，要設狀態幾等等細節，就讓我破防了，不斷的try and error。

還望請版主指教

**Comment by lienweb** [comment]
同學好，現在才看到你的提問~~
關於pathName那的確可能是沒有使用的屬性，感謝同學的發問讓我發現冗code。

針對stepper控制及整體架構來說，主要在前面使用純html/css/js實作時，會發現可以利用偵測當前所在頁碼，去顯示相對應的stepper畫面。
因此我的思考方向是會先寫出虛擬碼，確定所有的資料流與畫面流後，在開始切版 + 實作，一點方向提供給同學參考，希望有幫助到你~~

**Comment by MikeLee0358** [comment]
謝謝版主的回覆～

**Comment by MikeLee0358** [comment]
我研究了好幾個小時，還是沒辦法突破透過頁碼去變動v-for的方式。
請問：
  第2頁傳入stepper裡面，用template做邏輯控制。設置active＆checked的顯示方式。
  但是第3頁傳入，會卡到第二層的動態參數(v-for的緣故)，所以還是失敗了。
  看板主邏輯好精簡，不知道怎麼辦到的ＱＱ

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @CChaz, @swetaC1711, @samuelPapranec, @david-fernando, @apehex, @ggaabe, @Kris35hoog
